asciidoctor --destination-dir ./output  .\book.adoc ; .\output\book.html
dir -Recurse *.png -Exclude .\output\ |cp -Destination .\output -ErrorAction SilentlyContinue

# SIG # Begin signature block
# MIIEOQYJKoZIhvcNAQcCoIIEKjCCBCYCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUAPmEbakdsDKF9BqBkwpOwE6j
# lQ6gggJDMIICPzCCAaygAwIBAgIQrX6yGm7uxr9G2+CZjNNEiDAJBgUrDgMCHQUA
# MCwxKjAoBgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdDAe
# Fw0yMDA3MTIxMzA3MTBaFw0zOTEyMzEyMzU5NTlaMCAxHjAcBgNVBAMTFUF5ZW5k
# ZSBQb3dlclNoZWxsIENTQzCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEA+i1G
# 7ZtjZI5HemAsJI65oA0fr9Ymu/Y6UFlzQzrWRy3IdDh1snMxv+jrQMLFlrIFRwTn
# aIMpIMyMGy+rv/IipnsdUniREp0aL00JYk7yBZ0mSqkKNePpv0PQn4t7ZnYR0wau
# /J8HWgQ6cOGk+0mNOaSndKnE4l0b4ZvJZ1KQ5u0CAwEAAaN2MHQwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwXQYDVR0BBFYwVIAQrZIjhhzn/XQE2csNwBuM0KEuMCwxKjAo
# BgNVBAMTIVBvd2VyU2hlbGwgTG9jYWwgQ2VydGlmaWNhdGUgUm9vdIIQzU6ROMVR
# ZI9PvVA9bFB6tjAJBgUrDgMCHQUAA4GBAF0Av+UchSaLgi4A71Z/JkNCXciwi3rn
# DkCMCsFUnnQ42cIdj8vkbt8k91FV0NFQeERRXWbiyO8L6bTTXr7BGdKNKPsI0MvF
# rrUUwn5UKFZQTdW0bYkYJJtho0XaA0HvO71S4/bryniKTBYqb0nHj+cm6dZJ/RzM
# DN271MJVAqrDMYIBYDCCAVwCAQEwQDAsMSowKAYDVQQDEyFQb3dlclNoZWxsIExv
# Y2FsIENlcnRpZmljYXRlIFJvb3QCEK1+shpu7sa/RtvgmYzTRIgwCQYFKw4DAhoF
# AKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwGCisG
# AQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZIhvcN
# AQkEMRYEFJLm0oGMRJ0G89qnumwvcx/jZxcqMA0GCSqGSIb3DQEBAQUABIGASC/H
# 1axVtkaqSmh0uX6xgWkFKHb27tLeB4OVydgn17Xn2IimY/A3QqVrUaSBxh8K9QQW
# c71ydNSpAw4GE9nqjKODAZSZCIxUdZ4yRDZ/OBlmcrKayxI5wM6w4TyVqR83ehe2
# 2GZIE9bYUkBR/6/J43tcLH+GO7vPbOsoyvGf1gk=
# SIG # End signature block
